            - name: Add comment to Asana Task
  # You may pin to the exact commit or the version.
  # uses: Asana/comment-on-task-github-action@c0947e8462e93e32f5baa70b1ac983905258b53a
  uses: Asana/comment-on-task-github-action@v1.2
  with:
    # The Asana secret for the action. Read more about how to generate this secret at https://github.com/Asana/create-app-attachment-github-action#step-2-set-up-a-repository-secret-for-the-secret-token
    asana-secret: # default is 
    # List of allowed projects. The action will only add comments to tasks in these projects. Only one of allowed-projects or blocked-projects can be specified.
    allowed-projects: # optional, default is 
    # List of allowed projects. The action will not add comments to tasks or subtasks of tasks in any of these projects. Only one of allowed-projects or blocked-projects can be specified.
    blocked-projects: # optional, default is 
    # What comment the action should use. Learn how to customize this message at https://github.com/Asana/create-app-attachment-github-action#step-2-set-up-a-repository-secret-for-the-secret-token
    comment-text: # default is 
          
